# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

components:
  - ../../../components/azure/resources/gpu/1-H100
  # - ../../../components/hpa/vllm/token-latency # HPA is a work-in-progress

patches:
  - path: deployment.patch.yaml
    target:
      kind: Deployment
  - options:
      allowNameChange: true
    path: hpa.patch.yaml
    target:
      kind: HorizontalPodAutoscaler
