# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - ../base

components:
  - ../../../components/aws/resources/gpu/1-L4
  # - ../../../components/hpa/vllm/token-latency # HPA is a work-in-progress

patches:
  - path: deployment.patch.yaml
    target:
      kind: Deployment
  - options:
      allowNameChange: true
    path: hpa.patch.yaml
    target:
      kind: HorizontalPodAutoscaler
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: remove
        path: /spec/template/spec/nodeSelector
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          eks.amazonaws.com/compute-type: auto
